### ISSUE TITLE
Expose socket.io "server"

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [mauricemach/zappa#13]
Perhaps it can already be accessd from a zappa application but it's certainly escaped me after reading through the code and interrogating my app via REPL.

Basically it would be nice to access the socket.io "server" from an arbitrary location in the app without needing to resort to "def" hacks.

```
registry = {}
def registry: registry

get '/': -> 'Foo'

at connection: ->
  console.log "Connected: #{id}"
  broadcast 'connected', id: id

  registry.send = send

setTimeout(
  if registry.send
    registry.send 'foo'
, 1000)
```

As I mentioned, I'm convinced there's a way to do this already but it has alluded me...

**Comment by mauricemach** [comment]
You can get a reference to your zappa application with `myapp = app 'myapp'`. 

When your app is started, if you defined any `at` or `msg` handlers, socket.io will be initialized and you'll be able to access it at `myapp.ws_server`.

But since it is only created when your app starts, you will not be able to see it at the root scope.

I'm not sure though what is it that you're trying to achieve with the code you pasted here. If you could tell me what your final goal is, maybe I can show you another way of achieving it without resorting to accessing socket.io directly.

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
Basically we're instantiating a game engine inside our zappa "app" and have timers which push events to clients outside of the express/socket.io (get, at, msg) hooks provided by zappa.

So we need to be able to reference the socket.io "server" to broadcast events but I couldn't find a way to do this without creating the "registry" like I have in the code above...

**Comment by mauricemach** [comment]
In 0.2.0beta you have access to the socket.io server as `io` at the root and handler scopes.

The zappa function also returns it so you can use it from the outside. Ex.:

```
chat = require('zappa') ->
  # chat code here

console.log chat.app  # express server
console.log chat.io     # socket.io server
```
