### ISSUE TITLE
Mimic express/rails executable generator-server behaviour

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [mauricemach/zappa#14]
The express binary is able to generate apps as well as run them and I believe zappa should provide this facility.

For instance when running

```
zappa
```

should look for "app.coffee" in the current directory and operate as if the command were...

```
zappa app.coffee
```

When running zappa against a file that does not exist...

```
zappa does_not_exist
```

...it should create a scaffold application at the specific target (in this case in the folder "does_not_exist").

Perhaps there should be a "generate" flag to avoid costly mistakes.

```
zappa facebook_killer
> Error: ENOENT, No such file or directory 'facebook_killer'

zappa --generate facebook_killer
> generated new zappa app in facebook_killer
> generated facebook_killer/app.coffee
> generated facebook_killer/README.md
```

Although I'm not convinced this is necessary, it's more verbose/complex and it deviates from the accepted standard.

Furthermore...

```
zappa --template websockets facebook_killer
```

should utilise the websockets example from examples/websockets.coffee as a basis for the new zappa project.

Ultimately, I accept this is something @mauricemach and others might want to avoid. It's probably not a sinatra-ism and I must warn you that simpler frameworks like Sinatra are not largely part my background. Perhaps it may destroy the aura of simplicity about a zappa app. Nevertheless, I personally believe this is desirable behaviour.

Please chime in with your thoughts. I will begin work on the patch if @mauricemach approves, others are interested and it's not being attempted.

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
If more people are in favour of this than not I'll take a stab at it now...

**Comment by Soares** [comment]
+1, I'm interested to heart @mauricemach's reaction.

**Comment by mauricemach** [comment]
I've been hesitating to comment on this because I'm really torn on the direction I want to take in this regard, but screw it, here are my random thoughts so far:
- My goal with zappa is to reduce the boilerplate through a dynamic approach. The more successful zappa is, the less code we should have to write or generate. That said, I understand no matter how good zappa becomes, there will always be the need for static boilerplate generators, for many people, for many projects.
- I admire sinatra's approach of focusing on the basics, and letting other projects such as monk and padrino handle this kind of thing.
- On the other hand, it's nice to be able to install **one freaking package** and run with it. I admire this in rails.
- A good, homebrew generator would suck my energy and attention away from my focus with zappa (unfortunately, I'm not TJ), and I hate that. The bright side is that it could be perfectly optimized for zappa. But do we really need anything that a _good_ generic generator couldn't provide?
- Speaking of which, I did a little research on npm, and the best project I could find so far is [skeleton](https://github.com/edwardhotchkiss/skeleton). It's nice enough to be useful to us right now:

``` shell
npm install skeleton -g
skeleton add zappa git@github.com/user/zappachat.git
skeleton default zappa
```

Then:

``` shell
skeleton init myapp
```

Still I can think off the top of my head on: a shorter command, storing templates locally (skeleton does a git clone everytime I think), importing multiple templates from folders in one repo, and of course _options_. We probably should contribute to skeleton.
- At any rate, it's my responsibility to provide some complete boilerplate examples, be it for use with skeleton or a custom generator. The stuff at /examples doesn't really count, we need complete real life examples with package.json, .gitignore, Cakefile and all this annoying shit.
