### ISSUE TITLE
Automatically compile CoffeeScripts in the public directory

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [mauricemach/zappa#19]
At the moment if you have CoffeeScript as FILE.coffee in the public directory there is no way for it to be compiled and served as JavaScript.

It would be nice if hitting a non-existant FILE.js would render the CoffeeScript if there is a corresponding file.

**Comment by TrevorBurnham** [comment]
Hey pyrotechnick,

Since Zappa is built on top of Connect, what's really needed is a Connect plugin to do what you're describing. So I wrote one:

https://github.com/TrevorBurnham/connect-coffee

It's new and definitely still has some kinks, but please give it a whirl and let me know how it can be improved.

**Comment by esamattis** [comment]
This pull request would resolve this  https://github.com/mauricemach/zappa/pull/95
