### ISSUE TITLE
Override default "use" modules for express

### ISSUE THREAD

**Issue by shimaore** [mauricemach/zappa#25]
(This is something we discussed earlier in private emails.)

The idea is that one should be able to override the defaults for express's configuration (for example, maybe I don't want session management; or maybe I want to add more modules, etc.).

One possible implementation would be to modify "app" (I think) this way:
  https://gist.github.com/767922
so that one can do for example:

```
app "default", (server) ->
  server.use express.staticProvider("#{process.cwd()}/public")
  server.use require('./bodyDecoder')() # my own version of bodyDecoder
  server.use express.cookieDecoder()
  # no session
```

**Comment by abrookins** [comment]
Any traction on this?

**Comment by shimaore** [comment]
Updated diff against the latest (as of 2011-06-16) zappa  https://gist.github.com/1029206
or you can pull from git://stephane.shimaore.net/git/zappa.git

**Comment by abrookins** [comment]
Cool. I like it.

**Comment by mauricemach** [comment]
0.2.0beta comes with no default middleware, but instead a very concise API to define what you need:

```
use 'bodyParser', 'cookieParser', 'static', myown.middleware()
```

Which is equivalent to:

```
app.use express.bodyParser()
app.use express.cookieParser()
app.use express.static(__dirname + '/public')
app.use myown.middleware()
```

This second example is also an option to you in 0.2.0beta, since you have direct access to express' `app`.

The above are two extremes in a range of several levels of syntactic sugar. The examples below are all equivalent:

```
app.use express.static(__dirname + '/public')
use express.static(__dirname + '/public')
use static: __dirname + '/public'
use 'static'
```

Mix and match according to your needs.
