### ISSUE TITLE
"session requires the "secret" option string for security"

### ISSUE THREAD

**Issue by juliocesar** [mauricemach/zappa#28]
Hey ya. Lovely looking lib!

I went to give it a go, and whenever calling zappa on even the simplest example, I'm getting

```
→ zappa cuppa.coffee 

/usr/local/lib/node/.npm/connect/0.5.5/package/lib/connect/middleware/session.js:45
      throw new Error('session requires the "secret" option string for securit
            ^
Error: session requires the "secret" option string for security
```

Seems I'm missing something. Any ideas? Thanks!

**Comment by mauricemach** [comment]
Thanks for reporting! That was due to a change to the session middleware in connect 0.5.5. They're now throwing if you don't provide a secret key whereas before they just used a default value. I'll make it configurable later in zappa, but for now I'm using the same default value they used before.

You can install "edge":

```
npm install http://github.com/mauricemach/zappa/tarball/master
```

Or if you prefer to keep 0.1.4:

```
npm uninstall zappa express connect
npm install connect@0.5.4 express zappa
```

**Comment by juliocesar** [comment]
Champ! Thanks a lot. That was quick!

**Comment by bdarcus** [comment]
Am getting an error with that "edge" install instruction (maybe a temporary problem with github?). When do you expect this fix to be folded into a stable release?

**Comment by martypdx** [comment]
fyi - got this running on cygwin, had to:
- manually download tar.gz instead of $ npm install http//...
- run $ tar zxvf mauricemach-zappa-v0.1.4-1-g68e20cc.tar

Then I could do:
- $ npm install mauricemach-zappa-68e20cc/

But found out I had to first do:
- $ npm uninstall zappa

or it just kept running old code
