### ISSUE TITLE
Integrate 'watch' option with isaacs node-supervisor

### ISSUE THREAD

**Issue by zensatellite** [mauricemach/zappa#41]
I'm really liking Zappa and thinking of converting my current Express / CoffeeScript project over to it. One thing stopping me is the watch support for restarting the server when the app coffee file changes.

Unless I'm reading the cli.coffee file in 0.1.5 incorrectly, the watch option doesn't accept an argument, just applies itself to the main app file. It would be cool to allow a watch filelist or dir to be specified.

Rather than implementing this yourself you might be able to leverage isaacs's fine [node-supervisor](https://github.com/isaacs/node-supervisor) utility, which is what I'm currently using for restarting my Express server in connection with a CoffeeScript directory watch.

**Comment by krismolendyke** [comment]
Agreed.  I just moved beyond what I was comfortable with as a single file application.  Not watching `include` files is a bit of a hassle.  Supervisor is a good solution, but it'd be nice to have `include` watching be totally brainless!

**Comment by krismolendyke** [comment]
Actually, it looks like https://github.com/mauricemach/zappa/blob/master/src/cli.coffee#L53 should be taking care of this, but that's not the behavior I'm seeing currently for whatever reason.  Sorry to comment without checking it out first.  I'll investigate more when I get a chance.  Thanks!

**Comment by mauricemach** [comment]
The zappa command and the `-w` flag were introduced a long time ago when the node.js ecosystem was much less mature, now there are tons of excellent solutions to do anything in node. So instead of keep trying to reinvent the wheel in this area, I'm dropping the zappa command in 0.2.x, and making it easier to integrate zappa apps with this ecosystem.

So now, for reloading, one option is:

```
require('zappa') ->
  get '/': 'hi'

npm install run -g
runjs app.coffee
```

Of course, the interesting thing is that now you can use whatever tool you like better.

**Comment by zensatellite** [comment]
Excellent! It's good to see Zappa maturing - getting towards Roxy & Elsewhere ; )

**Comment by mauricemach** [comment]
:)

Maybe the codename for 0.3.x!
