### ISSUE TITLE
Arbitrary rendering engines

### ISSUE THREAD

**Issue by mauricemach** [mauricemach/zappa#5]

**Comment by goulash1971** [comment]
you mention in the readme that you're working on this ... 

I'm not sure how far you have gotten but (mainly because I'm looking at using HAML & SASS vs CoffeeKup & CCSS) I'm happy to start bashing some basic support into Zappa for consideration.  Alternatively, if you're some way through and/or have a design let me know.
- Stuart

**Comment by mauricemach** [comment]
I'm about to release 0.2.0beta with this support. Actually it will just use the view rendering system in express, so we'll have all of its features. The only differences in zappa will be the ability to automatically pass variables in `@` to templates, and to define templates in-file with the `view` function.

**Comment by goulash1971** [comment]
Funnily enough the "hack" that I had did the same :) ... I will hold off until you have 2.0 out - thanks.

**Comment by mauricemach** [comment]
If you arrived at the same solution independently, that's a good sign then. :) Did you just monkeypatch `express.View.prototype.exists` and `express.View.prototype.contents` too, or did you find a better solution?

**Comment by mauricemach** [comment]
Implemented in 0.2.0beta.
