### ISSUE TITLE
the magic locals conundrum

### ISSUE THREAD

**Issue by mauricemach** [mauricemach/zappa#74]
If you're interested in helping shape zappa's next developments, please read on and chime in. **Warning: text wall ahead!**

**Short version**: the drawbacks of zappa's "magic locals" approach are made worse with node 0.5.x. I'm exploring moving to a `@` (this) based API (`@get '/': -> @render 'index'`) to fix this, in this branch:

https://github.com/mauricemach/zappa/tree/this

**Long version**:

I'm calling "magic locals" zappa's current approach to provide convenience variables (`get`, `at`, `render`, `emit`, etc). Your functions are converted to string, manipulated to include these variables, and converted back to functions by use of the function constructor (`new Function(args, string)`).

This allows for unparalleled clean syntax and DRYness with no useless decoration characters (`@render`, `@redirect` etc), declarations (`(render, redirect, ...) ->`) or placeholders (`req.render`, `req.redirect`, etc). The drawbacks:
- Completely useless error messages (no meaningful filename, line or backtrace).
- The "normal" js scope is lost. Functions processed by zappa live in their own little bubble and external variables they'd normally have access to have to be explicitly included with `def foo`, `zappa {foo}, ->`, etc.
- Consequently, we also lose access to pseudo-globals such as `require` and `__filename`. Zappa currently provides fakes for these, and they're fine for many common scenarios, but are wrong in many others.

Node 0.5.x removes `require.paths`, which is what allows the fake `require` to _barely_ work. So if we keep the "magic locals" approach, to use require etc in the future, we'll have to either do it outside zappa blocks:

``` coffeescript
foo = require 'foo'
zappa {foo}, ->
```

Or pass them along manually:

``` coffeescript
zappa {require}, ->
  foo = require 'foo'
```

The alternative I'm considering is an approach I almost adopted when initially designing zappa, but discarded because magic locals seemed a better tradeoff. I'm talking about `@` (this) and `apply`:

``` coffeescript
require('zappa') ->
  # Look ma, no def!
  redis = require('redis').createClient()
  sum: (x, y) -> x + y

  # Mind the fat arrow.
  @configure development: =>
    @use errorHandler: {dumpExceptions: on}

  @helper requires_role: (role) ->
    @redirect '/login' unless @session.role is role

  @get '/': ->
    @foo = 'bar'
    @render 'index'

  @get '/redis': ->
    redis.get 'foo', (err, @foo) =>
      @render 'index'

  @get '/thisless-alternative': (c) ->
    redis.get 'foo', (err, foo) ->
      c.foo = foo
      c.render 'index'

  @get '/sum/:x/:y': ->
    @requires_role 'lord'
    @send sum(@x, @y)

  # `@on` instead of `at`.
  @on connection: ->
    @broadcast 'joined', {@id}
```

Pros:
- Normal js scope and node pseudo-globals preserved. No stinkin' `def` needed.
- Normal exceptions with correct filename, line (js line), and backtrace.
- Half the codebase (ok I'm kidding, but close).

Cons:
- @'s everywhere.
- data and methods mixed in the same namespace, or data relegated to an ugly namespace (`@data.foo`).
- this/@ is a very popular variable in js, so lots of fat arrows, or fallback to an ugly placeholder (`whatever.foo`, `whatever.render`, etc).

So fellow zappers, what do you think?

**Comment by jacobrask** [comment]
I think `z.foo` would be less confusing and less risk of conflict than `@foo`.

**Comment by mauricemach** [comment]
In the mentioned branch you're always able to use both. Like in the "thisless-alternative" example above. I personally find it ugly as hell, so I'd only use it as a last resort.

**Comment by smathy** [comment]
**Short Story:** +1 - definitely worth the tradeoffs.

## Long Story

### Pros

Any serious development is very hampered by the lack of a proper stacktrace, and I for one am really tiring of that problem.  For this reason alone I would happily accept the cons.

The preservation of globals and scope is also becoming an issue that I'm tiring of, and while nowhere near as important as a proper stacktrace, I definitely suffer pain again and again with that issue.

Half the codebase is always a good thing, but more from a bug/development perspective than anything else.  So still a good win, but not that important from a user perspective.

### Cons

@s everywhere - not an issue for me at all.  Yes, not as pretty/simple - but I use coffeekup instead of jade because better always outweighs prettier.

Mixing data and methods will take some care, but no more so than dealing with reserved keywords in any language.  Sounds like a (trivial) job for syntax highlighting to me.

Fat arrows - yes - a bit annoying.  Worth it though.

**Comment by shimaore** [comment]
Hmmm.. Couldn't we use http://nodejs.org/docs/v0.5.5/api/vm.html#vm.runInNewContext to implement the "locals magic"?

**Comment by shimaore** [comment]
Here's what it could look like: https://gist.github.com/1205211

**Comment by mauricemach** [comment]
@shimaore: I tried `runInNewContext` before, it's better than `new Function`, there's only a little problem... it's SLOW AS HELL. :) As in, orders of magnitude slower. I just gave it another try, to see if things improved in node 0.5.5, but running [this gist](https://gist.github.com/1205485) in my machine yielded the following results (in ms):

```
runInNewContext: 0.5599
new Function: 0.0001
apply: 0.0001
```

But even if performance was fine, the scope problem would persist. It doesn't have access to `require` etc or the local scope. Actually, it doesn't even have access to `console` (while `new Function` does).

@smathy: we're pretty much on the same page here. I tried to list all the pros and cons in a relatively neutral way to see what other people using zappa thought of it, but my actual opinion is the same as yours. And yes, the benefit I see in a simpler codebase is that it will be easier to spot/fix bugs and implement new features.

**Comment by shimaore** [comment]
@mauricemach: I don't think the performance of `runInNewContext` is relevant if it's called only once at startup, when `zappa.run()` re-compiles the code provided by coffeescript. From within the router, `apply` is the one that gets used (so that we can influence `this`).

I'd expect `console` can be provided as part of `context`. We're left with asking for
`zappa.run { module, require, .. }`
which I don't see as a killer (one-line in a web project; running multiple zappa instances in 1.0 was much worse) or monkey-patching node.js.

There is no solution to the '''external''' scope problem in that context. But I also don't understand it fully; can someone provide an example where

```
foo = ...
zappa.run { foo }, ->
    bar(foo)
```

cannot be rewritten

```
zappa.run ->
   foo = ...
   bar(foo)
```

please?

(When using `runInNewContext` the scope inside the `zappa.run` block is preserved, so `def` is gone.)

_Cons_

@s everywhere. Need a zappa-specific syntax definition for every text editor to hide them.

Higher chance of collision with `params` names (`@client`).

Fat arrows at random spots. We're replacing the difficulty of using a framework (express+socket.io) with the difficulty of figuring out where and when to use fat arrows, making it difficult for newcomers.

**Comment by shimaore** [comment]
Rewrote https://gist.github.com/1205211#file_explained.coffee to clarify what would be executed once (`runInNewContext`) vs what will be needed for each request.

**Comment by mauricemach** [comment]
Sorry, I didn't realize you were using `runInNewContext` only at the startup. But that's because as I understand it you _must_ use it for every route handler, otherwise how can you get hold of request-specific variables? In your example `render` is a global. To work with real requests, it would need access to the `res` object from express, which is request-specific. How would a global `render` reference a request-specific `res`?

**Comment by mauricemach** [comment]
https://gist.github.com/1206296

**Comment by goodside** [comment]
For whatever the opinion of a n00b is worth:

I find the @-peppered solution _much_ more appealing from the perspective of someone who is just learning to use the framework. For someone who only barely knows the API, it's annoying to look at other people's code and not be sure if something is a "magic" variable or not, and equally annoying to have to check whether you're using a magically influenced name when declaring your own locals.

Also, on a higher level, scope-altering magic just isn't the CoffeeScript way of doing things. I'm very much a Ruby person more than a Python person, but part of what attracted me to CoffeeScript is that it adopts the Python philosophy of being explicit about your module imports, and not allowing libraries to alter the language by effectively defining new reserved keywords. Scope pollution is hard by design, so variables never "leak" from one .coffee file to another, so you can always be sure your locals are what you think they are.

Fat arrows are an essential part of the language. It's reasonable to expect newcomers (and I say this as a newcomer) to understand them before using a CoffeeScript framework. Really, disguising the need for them by monkey-patching the language's scope semantics in this one particular case is doing newcomers a disservice, as it's training them to expect scope to work in ways that it generally doesn't. In fact, when I first started learning CoffeeScript, I actually _avoided_ zappa specifically for this reason.

**Comment by shimaore** [comment]
(1) I assume coffeekup also loses its magic in the process? (I would assume `zappa.adapter` will accept a coffeekup template as a string, not as a compiled javascript fragment. The alternative would be that `@` and `=>` also become required in coffeekup code, in which case `p`, `table`, .. become methods and aren't acceptable as template parameters.)

(2) In the scenario that `@` holds both methods and data, what happens if Zappa gets a new reserved keyword but I've been using that very name as a query parameter or template parameter?

```
get '/bar/:foo', -> # Zappa 5.0 introduces foo as a method.
  @new_data = "You said #{@foo}" # Oops, foo is now a Function
```

(3) Does this then mean that the only clean way out is to separate methods and data to make sure such collisions won't occur? Meaning `@` must remain the developer's namespace, Zappa's shouldn't pollute it:

```
couch = new couchdb(config.my_db.uri)
zappa.run (z) ->

  z.postrender ($) ->  # ($) is already required in the "this" branch.
      $('.bar').hide() if @name is 'why'

  z.get '/:name', (h) ->
    @foo = "You said #{@name}."
    couch.get @name, (err,data) =>
      if err
        return h.send error:err
      h.render 'this_template'
```

(4) What is wrong with accepting Zappa as its own language (which is the way I used to think of it in 1.0)? Zappa-as-a-language could handle scopes properly, accept the idea that `request` and its friends are keywords of the language (instead of magic locals, and thus still use `apply` everywhere), optimize parameters passing before writing javascript code out (no more `coffeescript_helpers`), provide proper source references when problems occur...

The compiler probably would look like a slightly modified version of the CoffeeScript compiler, with a dedicated runtime module that could be used by people who want to stick with plain CoffeeScript, using code like the one above. I guess that would give the best of both worlds, with plain magic for people who don't mind it, and full CoffeeScript orthodoxy otherwise.

**Comment by shimaore** [comment]
Proposition:
- Make Zappa into a regular, OO-type module (`zappa-lib`), with well-tested, well-documented, stable features. There is no 'magic' in that module; `get`/`post`/`postrender`/`view`/`at`/.. are methods of class `zappaServer`, an instance of which is the parameter of the callback for `zappa.run`; `render`/`send`/`request`/.. and (say) `data` are methods+data of `zappaRequest` (or whatever) which is the parameter of the callbacks for `get`/...; etc. Zappa-lib contains no rewriting at all (no `coffeescript_helpers` etc.) and can be used as a plain JavaScript module, just like Connect or Express.
- One or more higher-level implementations use zappa-lib. For example the model @mauricemach offered in his original post would (a) merge the methods of the object and the data of the request, and (b) make that object available as `this`. Another implementation, following the spirit of the 0.1 zappascript model, would offer keywords such as `request`, etc. and only keep data (query or template parameters) in `this`. These implementations can use standard inheritance from zappa-lib, or may do rewriting with helpers, or might implement a specific parser, or whatever. In any case they are just fancy wrappers for zappa-lib. One or more of them might be offered with standard Zappa to make for inspiring documentation.

**Comment by mauricemach** [comment]
@goodside: Thanks for sharing your perspective. I think we're meeting from different directions. I actually miss ruby's crazy flexibility, it allowed for original leaps in expressiveness such as sinatra. Without it, what would express be inspired by?

That said, I also think that if we can achieve similar levels of expressiveness using very commonly understood language mechanisms instead of heavy-metal metaprogramming, that's always better. Especially if the metaprogramming capabilities in the language/runtime suck. Yes, it's much better to have to deal with common CoffeeScript/JavaScript gotchas such as the fat arrow than zappa-specific gotchas such as `def`.

**Comment by mauricemach** [comment]
@shimaore:

(1) CoffeeKup is not necessarily touched, actually it's preferably left intact. The two libs have very different requirements and I think the "magic locals" approach still gets CK the best bang for the buck. The biggest problem with zappa + `new Function` is that it needs one for each handler, and the impact of destroying the scope is big. In CK it is only done once, and at a point where it doesn't really matter - we already expect templates to operate in a special scope anyway.

(2/3) Yeah that sucks, but you're not required to use the root context for your variables, you can use `@data.foo` or locals + explicit forwarding if you want, and have your peace of mind. Only if you're obssessive about readability like me and keep your vars at the root, you'll have to put up with the extra concern when upgrading.

(4) Zappa as a language is an interesting concept, but outside the scope of my capabilities and motivation. I just need a proper (from a minimalist's point of view) interface to node web development, provided as the leanest possible implementation and abstraction on top of the standard node environment. Which leads us to…

(zappa-lib) I appreciate the benefits of abstraction, encapsulation, and having options. But I also know how energy/attention sucking it can get maintaining these layers and alternative interfaces. Zappa is about focus and simplicity, and I'd rather keep one very straightforward implementation if possible.

You seem to be willing to move mountains to avoid the "@-peppered" solution, but I'm not sure I understand what are all the problems you see in it. Is it just the data namespace thing, or is there something else?

**Comment by rdrey** [comment]
Agree with @smathy and @goodside

Nothing wrong with the @'s and fat arrows. Stacktraces would be sweet from a noobie perspective, too. I do think that learning when to use the right kind of arrow is probably a little harder than just accepting that you need def's for zappa's magic to work, though. (But learning when to do a closure with a fat arrow is required for more serious coffeescript work in any case, eventually.)

Another random point: When one of my buddies saw the function-rewriting zappa is currently doing, he thought it was too hacky and that immediately scared him away from the whole coffeescript & node stack. I'm still convincing him to give zappa a shot and ignore the ugly-looking magic.

**Comment by mauricemach** [comment]
@rdrey: oh noes, what have I done! :) Tell him that even if zappa is too hacky to his taste, that really shouldn't turn him away from checking out CoffeeScript + node. It's a really great combo there's plenty of choice on frameworks, of many different styles.

**Comment by mauricemach** [comment]
OK, so I'm preparing the "z@ppa" branch to be released as 0.3.0 soon, unless someone comes up with a solution to make locals viable.

With all the API in the `@`, automatically putting all input variables there ceases to be an obvious choice, so I'm making it an option (`enable 'autoimport'`). Even if enabled, it will never overwrite already existing variables such as `@request` or your helpers. In default zappa, input will be accessible as `foo = @query.foo`. This `@query` is a new shortcut, as well as `@body` and `@params` (express' `request.params`). For websockets, it's `@data`.

Same thing for automatically relaying variables to templates. In default zappa, use `@render index: {foo, zig, ping}`. When using `enable 'autoexport'`, all variables in the `@` that are not from the framework will be forwarded as in 0.2.x.

**Comment by mauricemach** [comment]
To summarize and document the problems with magic locals (both the current implementation and a hypothetical one with the vm module):
- **Meaningless backtrace**. Completely useless in the current implementation (`eval at <anonymous> (/path/to/zappa/lib/zappa.js:35`). The vm module fares a little better but still each handler would be like a virtual file with virtual (wrong) line numbers.
- **Performance (only in the the case of the vm module)**. The root scope (`get`, `at`, etc) is piece of cake since it's only run once, but to have handler-specific locals (`render`, `redirect`, etc), we'd have to `.runInNewContext` at each request, which is prohibitively slow.
- **Lost closures** in both implementations. Mechanisms such as `def` necessary to simulate them.
- **Lost `require`, `__filename`, etc** in both implementations.

**Comment by mauricemach** [comment]
Scratch that (`autoimport`/`autoexport`). Using a [much better idea](https://github.com/mauricemach/zappa/issues/84) from @shimaore.

**Comment by smathy** [comment]
This can be closed now.
