### ISSUE TITLE
blog post has installation instructions error :]

### ISSUE THREAD

**Issue by nthx** [mauricemach/zappa#76]
Here: http://thechangelog.com/post/1582034775/zappa-razor-sharp-dsl-for-modern-web-apps
there is an error on how to use zappa. I've spent some time to look for "zappa" executable ;)

$ zappa cuppa.coffee
=> App "default" listening on port 5678...

And should be this instead - well at least it works with current GH code

$ coffee cuppa.coffee
=> App "default" listening on port 5678...

So if you can fix the blog post, as it's quite top result on Google :)
Cheers!

**Comment by mauricemach** [comment]
Thanks for the feedback, but it's not an error, the blog post is about zappa 0.1.x. It wouldn't make much sense to edit all blog posts in the interwebs about rails 2.x because we're now at 3.x, would it? :)

By the way, I'm not involved with that blog. I love it as a reader but I don't have any role in it.

It being a top google result is a problem, but right next to it is the readme on github (with updated installation/running instructions at the top), and the recently released zappajs.org is climbing its way up.

**Comment by nthx** [comment]
I see. Thanks for info. True..
I've found zappajs.org later on anyway
CU - keep up the good work :)
